main: me.thebereavingbee.Juggernaut.Main
name: Juggernaut
version: 1.0
description: This plugin is a self contained minigame.
api-version: 1.13
load: POSTWORLD
author: thebereavingbee
commands: 
  juggernaut:
    aliases: jug